[package]
name = "file-organizer"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.39"
walkdir = "2.5.0"
twox-hash = "2.1.0"
serde_json = "1.0.134"
clap = { version = "4.5", features = ["derive"] }
